/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package top;

import java.util.ArrayList;
import javax.swing.Box.*;
import java.awt.Dimension;

/**
 *
 * @author dudes
 */
public class Block extends javax.swing.JPanel {

    /**
     * Creates new form Block
     */
    public Block() {
        initComponents();
        initTime();
    }
    
    public Block(ArrayList<Activity> Today) {
        initComponents();
        initTime();
        for (int i = 0; i < Today.size(); i++)
            {
                Activity temp = Today.get(i);
                temp.getDuration();
            }
    }

    
    private void initTime()
    {
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel3.add(filler1, new java.awt.GridBagConstraints());
        //box = Filler(Dimension());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.VERTICAL;
        for (int j = 0; j < 96; j++)
        {
            gbc.gridy = j;
            jPanel3.add(new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767)), gbc);
            //jScrollPane1.add(new Box.Filler(0,0,0), gbc);
        }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(48, 0, 0, 5));

        jLabel1.setText("12:00");
        jPanel2.add(jLabel1);

        jLabel2.setText("12:30");
        jPanel2.add(jLabel2);

        jLabel3.setText("1:00");
        jPanel2.add(jLabel3);

        jLabel4.setText("1:30");
        jPanel2.add(jLabel4);

        jLabel5.setText("2:00");
        jPanel2.add(jLabel5);

        jLabel6.setText("2:30");
        jPanel2.add(jLabel6);

        jLabel7.setText("3:00");
        jPanel2.add(jLabel7);

        jLabel8.setText("3:30");
        jPanel2.add(jLabel8);

        jLabel9.setText("4:00");
        jPanel2.add(jLabel9);

        jLabel10.setText("4:30");
        jPanel2.add(jLabel10);

        jLabel11.setText("5:00");
        jPanel2.add(jLabel11);

        jLabel12.setText("5:30");
        jPanel2.add(jLabel12);

        jLabel13.setText("6:00");
        jPanel2.add(jLabel13);

        jLabel14.setText("6:30");
        jPanel2.add(jLabel14);

        jLabel15.setText("7:00");
        jPanel2.add(jLabel15);

        jLabel16.setText("7:30");
        jPanel2.add(jLabel16);

        jLabel17.setText("8:00");
        jPanel2.add(jLabel17);

        jLabel18.setText("8:30");
        jPanel2.add(jLabel18);

        jLabel19.setText("9:00");
        jPanel2.add(jLabel19);

        jLabel20.setText("9:30");
        jPanel2.add(jLabel20);

        jLabel21.setText("10:00");
        jPanel2.add(jLabel21);

        jLabel22.setText("10:30");
        jPanel2.add(jLabel22);

        jLabel23.setText("11:00");
        jPanel2.add(jLabel23);

        jLabel24.setText("11:30");
        jPanel2.add(jLabel24);

        jLabel25.setText("12:00");
        jPanel2.add(jLabel25);

        jLabel26.setText("12:30");
        jPanel2.add(jLabel26);

        jLabel27.setText("1:00");
        jPanel2.add(jLabel27);

        jLabel28.setText("1:30");
        jPanel2.add(jLabel28);

        jLabel29.setText("2:00");
        jPanel2.add(jLabel29);

        jLabel30.setText("2:30");
        jPanel2.add(jLabel30);

        jLabel31.setText("3:00");
        jPanel2.add(jLabel31);

        jLabel32.setText("3:30");
        jPanel2.add(jLabel32);

        jLabel33.setText("4:00");
        jPanel2.add(jLabel33);

        jLabel34.setText("4:30");
        jPanel2.add(jLabel34);

        jLabel35.setText("5:00");
        jPanel2.add(jLabel35);

        jLabel36.setText("5:30");
        jPanel2.add(jLabel36);

        jLabel37.setText("6:00");
        jPanel2.add(jLabel37);

        jLabel38.setText("6:30");
        jPanel2.add(jLabel38);

        jLabel39.setText("7:00");
        jPanel2.add(jLabel39);

        jLabel40.setText("7:30");
        jPanel2.add(jLabel40);

        jLabel41.setText("8:00");
        jPanel2.add(jLabel41);

        jLabel42.setText("8:30");
        jPanel2.add(jLabel42);

        jLabel43.setText("9:00");
        jPanel2.add(jLabel43);

        jLabel44.setText("9:30");
        jPanel2.add(jLabel44);

        jLabel45.setText("10:00");
        jPanel2.add(jLabel45);

        jLabel46.setText("10:30");
        jPanel2.add(jLabel46);

        jLabel47.setText("11:00");
        jPanel2.add(jLabel47);

        jLabel48.setText("11:30");
        jPanel2.add(jLabel48);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.05;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());
        jPanel3.add(filler1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
