/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package top;

import java.time.LocalDate;

/**
 *
 * @author dudes
 */
public class DayPanel extends javax.swing.JPanel {

    
    public DayPanel() {    
        initComponents();
        DateNum.setText("69");
        label1.setText("bungus");
    }
    
    /**
     * Creates new form Day
     * @param now
     */
    public DayPanel(LocalDate now, Integer eventCount) {
        initComponents();
        DateNum.setText(Integer.toString(now.getDayOfMonth()));
        label1.setText(Integer.toString(eventCount));
    }
    
    public void setText(String date, String count)
    {
        DateNum.setText(date);
        label1.setText(count);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        DateNum = new java.awt.Label();
        label1 = new java.awt.Label();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        DateNum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DateNum.setText("bungus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(DateNum, gridBagConstraints);

        add(jPanel1);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("label1");
        label1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                label1PropertyChange(evt);
            }
        });
        add(label1);
        add(filler1);
    }// </editor-fold>//GEN-END:initComponents

    private void label1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_label1PropertyChange
        // TODO add your handling code here:
        validate();
        repaint();
    }//GEN-LAST:event_label1PropertyChange

    //private ArrayList<Activity> date;
    // date.indexOf(Activity.getDate() == selectedDay);
    // date.lastIndexOf(Activity.getDate() == selectedDay+1);
    private LocalDate selectedDay;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label DateNum;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
