/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package top;

import java.time.LocalDate;

/**
 *
 * @author dudes
 */
public class DayPanel extends javax.swing.JPanel {

    
    public DayPanel() {    
        initComponents();
        DateNum.setText("69");
        label1.setText("bungus");
    }
    
    /**
     * Creates new form Day
     * @param now
     */
    public DayPanel(LocalDate now) {
        initComponents();
        DateNum.setText(Integer.toString(now.getDayOfMonth()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        DateNum = new java.awt.Label();
        label1 = new java.awt.Label();

        setLayout(new java.awt.CardLayout());
        add(filler1, "card4");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        DateNum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DateNum.setText("bungus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(DateNum, gridBagConstraints);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("label1");
        jPanel1.add(label1, new java.awt.GridBagConstraints());

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    //private ArrayList<Activity> date;
    // date.indexOf(Activity.getDate() == selectedDay);
    // date.lastIndexOf(Activity.getDate() == selectedDay+1);
    private LocalDate selectedDay;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label DateNum;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
